/**
 * Generate a 1-page PDF inspection report.
 *
 * NOTE: Requires jsPDF to be installed: npm install jspdf
 * If jsPDF is not available, falls back to a simple text-based approach.
 */

import type { InspectionFile } from '@/core/models/inspection-file';

/** Minimal jsPDF interface for our usage. */
interface JsPDFDoc {
  setFontSize(size: number): void;
  setFont(name: string, style: string): void;
  setTextColor(gray: number): void;
  text(text: string, x: number, y: number, opts?: { align?: string }): void;
  addImage(data: string, format: string, x: number, y: number, w: number, h: number): void;
  save(filename: string): void;
}

export async function exportReportAsPdf(file: InspectionFile, canvas: HTMLCanvasElement | null) {
  try {
    // Dynamic import of jsPDF to avoid build errors if not installed
    // jsPDF is optional - use runtime import to prevent bundler resolution
    const jsPDFModule = await Function('return import("jspdf")')() as { default: new (orientation: string, unit: string, format: string) => JsPDFDoc };
    const jsPDF = jsPDFModule.default;
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    let y = 15;

    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Lancelot Inspection Report', pageWidth / 2, y, { align: 'center' });
    y += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120);
    doc.text(new Date().toLocaleString(), pageWidth / 2, y, { align: 'center' });
    doc.setTextColor(0);
    y += 10;

    // File info (2 columns)
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('File Information', 15, y);
    y += 6;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const info = [
      ['Lot ID', file.identity.lotId],
      ['Wafer ID', file.identity.waferId],
      ['Device ID', file.identity.deviceId],
      ['Equipment', `${file.inspectionSetup.stationId.vendor} ${file.inspectionSetup.stationId.model}`],
      ['Wafer Diameter', `${(file.waferGeometry.waferDiameter / 1000).toFixed(0)} mm`],
      ['Die Pitch', `${file.waferGeometry.diePitch[0]} x ${file.waferGeometry.diePitch[1]} um`],
    ];

    for (const [label, value] of info) {
      doc.setFont('helvetica', 'bold');
      doc.text(label + ':', 15, y);
      doc.setFont('helvetica', 'normal');
      doc.text(value, 55, y);
      y += 5;
    }
    y += 5;

    // WaferMap image
    if (canvas) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('Wafer Map', 15, y);
      y += 4;

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = 120;
      const imgHeight = (canvas.height / canvas.width) * imgWidth;
      const imgX = (pageWidth - imgWidth) / 2;
      doc.addImage(imgData, 'PNG', imgX, y, imgWidth, imgHeight);
      y += imgHeight + 8;
    }

    // Statistics
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Statistics', 15, y);
    y += 6;

    const testedDies = file.dieMap.filter((d) => d.status === 'tested');
    const cleanDies = testedDies.filter((d) => d.defectCount === 0);
    const yieldPct = testedDies.length > 0 ? ((cleanDies.length / testedDies.length) * 100).toFixed(1) : 'N/A';

    const stats = [
      ['Total Defects', file.defects.length.toLocaleString()],
      ['Defect Classes', String(file.classLookup.length)],
      ['Dies in Map', String(file.dieMap.length)],
      ['Die Yield', `${yieldPct}%`],
    ];

    doc.setFontSize(9);
    for (const [label, value] of stats) {
      doc.setFont('helvetica', 'bold');
      doc.text(label + ':', 15, y);
      doc.setFont('helvetica', 'normal');
      doc.text(value, 55, y);
      y += 5;
    }

    // Class breakdown
    if (file.classLookup.length > 0) {
      y += 3;
      doc.setFont('helvetica', 'bold');
      doc.text('Class Breakdown:', 15, y);
      y += 5;

      const classCounts = new Map<number, number>();
      for (const d of file.defects) {
        if (d.classNumber != null) {
          classCounts.set(d.classNumber, (classCounts.get(d.classNumber) ?? 0) + 1);
        }
      }

      doc.setFont('helvetica', 'normal');
      for (const cls of file.classLookup) {
        const count = classCounts.get(cls.classNumber) ?? 0;
        doc.text(`  ${cls.className}: ${count.toLocaleString()}`, 15, y);
        y += 4;
        if (y > 275) break;
      }
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Lancelot v0.1.0', pageWidth / 2, 290, { align: 'center' });

    doc.save(file.source.fileName.replace(/\.\w+$/, '') + '_report.pdf');
  } catch {
    // jsPDF not installed - fall back to alert
    alert('PDF export requires jsPDF. Install with: npm install jspdf');
  }
}
